# ArgoCD Application — kube-prometheus-stack
# GitOps managed: ArgoCD syncs this automatically
# Uses multi-source: chart from Helm repo + values from Git repo

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: Helm chart from prometheus-community
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "82.10.1"
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/sre-observability-stack/monitoring/kube-prometheus-stack/values.yaml
        values: |
          grafana:
            persistence:
              storageClassName: gp2
            adminPassword: "Admin@1234!"
          prometheus:
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: gp2
          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: gp2

    # Source 2: Values files from Git repo (referenced as $values above)
    - repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
