# ArgoCD Application — kube-prometheus-stack
# GitOps managed: ArgoCD syncs this automatically
# DO NOT run helm upgrade manually - let ArgoCD manage it

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "82.10.1"
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - $values/sre-observability-stack/monitoring/kube-prometheus-stack/values.yaml
      values: |
        grafana:
          persistence:
            storageClassName: gp2
          adminPassword: "Admin@1234!"
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp2
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp2

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "82.10.1"
      helm:
        releaseName: kube-prometheus-stack

    - repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false       # Don't auto-prune monitoring (safety)
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # Required for large CRDs
