apiVersion: v2
name: demo-app
description: A Helm chart for Demo Microservice Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - demo
  - microservice
  - nodejs
maintainers:
  - name: Shaik Shafivulla
    email: shafivullashaik916@gmail.com
