# Demo Application - Managed by ArgoCD

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: main
    path: app-microservice-demo/helm
    helm:
      valueFiles:
        - ../../gitops-eks-platform/environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica changes from HPA
