---
# Kyverno — Policy Engine
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "policy"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers: [/webhooks]
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers: [/webhooks]

---
# External Secrets Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "secret-management"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
# cert-manager — TLS Certificate Automation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "certificate-management"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
# Falco — Runtime Security
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "runtime-security"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/falco
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
