---
# KEDA — Event-Driven Pod Autoscaler
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "pod-autoscaling"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
# Karpenter — Node Autoscaler
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "node-autoscaling"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
# VPA — Vertical Pod Autoscaler
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "vertical-autoscaling"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/vpa
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]

---
# HA Configs — PDBs and Topology Spread
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ha
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  labels:
    app.kubernetes.io/component: "high-availability"
spec:
  project: default
  source:
    repoURL: https://github.com/shafivullashaik-tech-ops/devops-portfolio.git
    targetRevision: feature/llmops-rag-gateway
    path: gitops-eks-platform/platform-services/ha
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers: [/spec/replicas]
